name: CICD Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - uses: actions/download-artifact@v3
      with:
        name: my-trained-model
        path: sentiment_model/trained_models
    - uses: actions/download-artifact@v3
      with:
        name: my-trained-tokenizer
        path: sentiment_model/trained_tokenizer
    - name: Install dependencies
      run: pip install --upgrade build
    - name: Build package
      run: python -m build
    - uses: actions/upload-artifact@v3
      with:
        name: my-build-package
        path: dist/*.whl
        retention-days: 1

  push-image:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v3
      with:
        name: my-build-package
        path: sentiment_model_api

    - name: Login to Docker hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build the Docker image for Fastapi app
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
      run: docker build . -f Dockerfile -t $DOCKER_USER/sentiment-fastapi:latest

    - name: Push the Docker Image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
      run: docker push $DOCKER_USER/sentiment-fastapi

    - name: Logout to Docker hub
      run: docker logout

  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker pull $DOCKER_USER/sentiment-fastapi:latest
      - name: Delete Old Docker Container
        run: sudo docker rm -f sentiment-fastapi-container || true
      - name: Run Docker Container
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker run -itd -p 8001:8001 --name sentiment-fastapi-container $DOCKER_USER/sentiment-fastapi:latest
