name: Sentiment Classification Training and Testing
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements/requirements.txt
    - name: Train and save pipeline
      run: python sentiment_model/train_model.py
    - uses: actions/upload-artifact@v3
      with:
        name: my-trained-model
        path: sentiment_model/trained_models
    - uses: actions/upload-artifact@v3
      with:
        name: my-trained-tokenizer
        path: sentiment_model/trained_tokenizer

  test:
    needs: train
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: actions/download-artifact@v3
      with:
        name: my-trained-model
        path: sentiment_model/trained_models
    - uses: actions/download-artifact@v3
      with:
        name: my-trained-tokenizer
        path: sentiment_model/trained_tokenizer
    - name: Install dependencies
      run: pip install -r requirements/test_requirements.txt
    - name: Test with pytest
      run: pytest
